"""empty message

Revision ID: b574042161ae
Revises: 
Create Date: 2017-08-13 13:09:45.797895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b574042161ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nyc_air_data', sa.Column('Measure', sa.Text(), nullable=True))
    op.drop_column('nyc_air_data', 'measure')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nyc_air_data', sa.Column('measure', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('nyc_air_data', 'Measure')
    # ### end Alembic commands ###
